name: tutorial-fastapi
services:
    api:
        build: . 
        ports: 
            - 8000:8000
    db:
        image: postgres:15-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data/
            - ./app/queries/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
volumes:
  db:
    driver: local